// packages/create-pledge-app/templates/vue/app/layout.vue
<template>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>PledgeStack Vue App</title>
    </head>
    <body>
      <slot />
    </body>
  </html>
</template>

<script setup lang="ts">
// Root layout — wraps all pages
</script>

// packages/create-pledge-app/templates/svelte/app/layout.svelte
<script lang="ts">
  // Root layout — wraps all pages
  let { children } = $props();
</script>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PledgeStack Svelte App</title>
  </head>
  <body>
    {@render children()}
  </body>
</html>
