// packages/create-pledge-app/templates/solid/app/layout.tsx
import { type ParentComponent } from 'solid-js';

const Layout: ParentComponent = (props) => {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>PledgeStack Solid App</title>
      </head>
      <body>
        {props.children}
      </body>
    </html>
  );
};

export default Layout;

// packages/create-pledge-app/templates/svelte/app/layout.svelte
<script lang="ts">
  // Root layout — wraps all pages
  let { children } = $props();
</script>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PledgeStack Svelte App</title>
  </head>
  <body>
    {@render children()}
  </body>
</html>
