// packages/create-pledge-app/templates/solid/app/page.tsx
import { type Component } from 'solid-js';

const Page: Component = () => {
  return (
    <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
      <div class="text-center">
        <h1 class="text-4xl font-bold text-gray-900 mb-4">Welcome to PledgeStack</h1>
        <p class="text-lg text-gray-600 mb-8">Built with Solid.js + PledgeStack</p>
        <a
          href="https://pledgestack.dev/docs"
          class="inline-block px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
        >
          Get Started →
        </a>
      </div>
    </div>
  );
};

export default Page;

// packages/create-pledge-app/templates/svelte/app/page.svelte
<script lang="ts">
  // Svelte 5 page component
</script>

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
  <div class="text-center">
    <h1 class="text-4xl font-bold text-gray-900 mb-4">Welcome to PledgeStack</h1>
    <p class="text-lg text-gray-600 mb-8">Built with Svelte 5 + PledgeStack</p>
    <a
      href="https://pledgestack.dev/docs"
      class="inline-block px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
    >
      Get Started →
    </a>
  </div>
</div>
